name: CI
on:
  push:
    branches: [main, develop]
    paths: ["src/**", "tests/**", ".github/workflows/**"]
  pull_request:
    branches: [main, develop]
    paths: ["src/**", "tests/**", ".github/workflows/**"]
  schedule:
    # Scheduled Daily CI
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  CI_black-flake8-pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          poetry install -n
          poetry update -n

      - name: Run black format check
        run: poetry run black src tests --check --diff --verbose

      - name: Run flake8 lint check
        run: poetry run flake8 src tests --max-line-length=88 --ignore=E203,W503,W504

      - name: Run pytest
        run: poetry run pytest tests --tb=line --cov=src --cov-report=xml --cov-report=term

      - name: Upload coverage to Codecov
        if: ${{ matrix.python-version==3.8 }} && ${{ matrix.os=='ubuntu-latest' }}
        uses: codecov/codecov-action@v2
        with:
          name: pytest-codecov
          files: coverage.xml
          fail_ci_if_error: true
