name: Publish to PyPI
on:
  release:
    types: [released]

jobs:
  publish_to_pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    env:
      PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry poetry-dynamic-versioning
      - name: Build
        run: poetry build

      - name: Publish
        run: poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD
